package insight

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const memoryFileName = "MEMORY.md"
const memoryDir = ".coden"

// WriteMemoryFile regenerates .coden/MEMORY.md in workspaceRoot from the
// current session's active (non-superseded) insights.
//
// The file is rewritten atomically on each call so it always reflects the
// latest insight state. It is intended to be called asynchronously after
// each workflow turn completes.
//
// File layout:
//
//	# Session Memory
//	_Last updated: <timestamp>_
//
//	## Decisions
//	- **<title>** (confidence: 0.9): <content>
//
//	## Findings
//	...
func WriteMemoryFile(workspaceRoot, sessionID string, store Store) error {
	insights := store.ListBySession(sessionID, 0)
	if len(insights) == 0 {
		return nil
	}

	// Filter superseded entries.
	var active []Insight
	for _, ins := range insights {
		if ins.SupersededBy == "" {
			active = append(active, ins)
		}
	}
	if len(active) == 0 {
		return nil
	}

	// Group by category, sort within each group by confidence desc.
	byCategory := make(map[Category][]Insight)
	for _, ins := range active {
		byCategory[ins.Category] = append(byCategory[ins.Category], ins)
	}
	order := []Category{CategoryDecision, CategoryDesign, CategoryFinding, CategoryComparison}
	for _, cat := range order {
		sort.Slice(byCategory[cat], func(i, j int) bool {
			if byCategory[cat][i].Confidence != byCategory[cat][j].Confidence {
				return byCategory[cat][i].Confidence > byCategory[cat][j].Confidence
			}
			return byCategory[cat][i].CreatedAt.After(byCategory[cat][j].CreatedAt)
		})
	}

	var sb strings.Builder
	sb.WriteString("# Session Memory\n")
	sb.WriteString(fmt.Sprintf("_Last updated: %s_\n\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	sb.WriteString("This file is auto-generated by CodeN. It summarises decisions and findings\n")
	sb.WriteString("from previous workflow turns so workers can stay coherent across turns.\n\n")

	for _, cat := range order {
		entries := byCategory[cat]
		if len(entries) == 0 {
			continue
		}
		heading := strings.Title(string(cat)) + "s" //nolint:staticcheck
		sb.WriteString(fmt.Sprintf("## %s\n\n", heading))
		for _, ins := range entries {
			tags := ""
			if len(ins.Tags) > 0 {
				tags = " `" + strings.Join(ins.Tags, "` `") + "`"
			}
			sb.WriteString(fmt.Sprintf("- **%s** (%.0f%% confidence)%s\n  %s\n\n",
				ins.Title,
				ins.Confidence*100,
				tags,
				ins.Content,
			))
		}
	}

	dir := filepath.Join(workspaceRoot, memoryDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir .coden: %w", err)
	}

	path := filepath.Join(dir, memoryFileName)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write memory tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename memory file: %w", err)
	}

	return nil
}
